/*
 * Esta clase muestra el menú para la opción de modificar con un JComboBox dentro de un JFrame.
 * Consta de un constructor vacío, dos botones con sus acciones y un JComboBox para elegir las
 * diferentes opciones.
 */
package com.alumnos;

import com.alumnos.ListaAlumnos;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * El autor de esta aplicación es: Moisés Rey Jelusich
 * @author moises
 */

public class MenuModificar extends javax.swing.JFrame {
    //Constructor vacío.
    public MenuModificar() {
        initComponents(); 
        setTitle("Menu de modificar alumnos");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); //Para cerrar la ventana y volver al menú principal.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_foto_animada = new javax.swing.JLabel();
        jComboBox_menu_modificar = new javax.swing.JComboBox<>();
        jLabel_titulo_modificar = new javax.swing.JLabel();
        jButton_volver = new javax.swing.JButton();
        jButton_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox_menu_modificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_menu_modificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige el campo a modificar:", "Nombre", "DNI", "Telefono", "Direccion", "Email", "Edad", "Provincia", "Fecha Matriculacion", "Estado Civil", "Estudios" }));

        jLabel_titulo_modificar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_titulo_modificar.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_titulo_modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo_modificar.setText("MODIFICAR ALUMNOS");

        jButton_volver.setText("VOLVER");
        jButton_volver.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volverActionPerformed(evt);
            }
        });

        jButton_aceptar.setText("ACEPTAR");
        jButton_aceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel_titulo_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox_menu_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel_foto_animada, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel_titulo_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_foto_animada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jComboBox_menu_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volverActionPerformed
        dispose();  //Para volver al menú anterior.
    }//GEN-LAST:event_jButton_volverActionPerformed

    private void jButton_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarActionPerformed
        try {
            //Se crea el objeto la de la clase ListaAlumnos para poder llamar al método modificarAlumnos.
            ListaAlumnos la = new ListaAlumnos();
            la.modificarAlumnos();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error, no se ha podido modificar el campo seleccionado de los alumnos", "ERROR", 0);
        }
    }//GEN-LAST:event_jButton_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton_aceptar;
    public static javax.swing.JButton jButton_volver;
    public static javax.swing.JComboBox<String> jComboBox_menu_modificar;
    public static javax.swing.JLabel jLabel_foto_animada;
    private javax.swing.JLabel jLabel_titulo_modificar;
    // End of variables declaration//GEN-END:variables
}
