/*
 * Esta clase muestra un Jframe con un JComboBox para poder elegir los campos
 * a modificar de los usuarios.
 */
package com.usuarios;

import com.usuarios.ListaUsuarios;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
* El autor de esta aplicación es: Moisés Rey Jelusich
 * @author moises
 */
public class MenuModificarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MenuModificarUsuario
     */
    public MenuModificarUsuario() {
        initComponents();
        setTitle("Menu de modificar usuarios");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); //Para cerrar la ventana y volver al menú principal.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo_modificar_usuario = new javax.swing.JLabel();
        jComboBox_menu_modificar_usuarios = new javax.swing.JComboBox<>();
        jButton_volver_usuarios = new javax.swing.JButton();
        jButton_aceptar_usuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_titulo_modificar_usuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_titulo_modificar_usuario.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_titulo_modificar_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_titulo_modificar_usuario.setText("MODIFICAR USUARIOS");

        jComboBox_menu_modificar_usuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox_menu_modificar_usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige el campo a modificar:", "Nombre", "Clave" }));

        jButton_volver_usuarios.setText("VOLVER");
        jButton_volver_usuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_volver_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_volver_usuariosActionPerformed(evt);
            }
        });

        jButton_aceptar_usuarios.setText("ACEPTAR");
        jButton_aceptar_usuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_aceptar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptar_usuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel_titulo_modificar_usuario)
                        .addComponent(jButton_aceptar_usuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton_volver_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_menu_modificar_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel_titulo_modificar_usuario)
                .addGap(41, 41, 41)
                .addComponent(jComboBox_menu_modificar_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_volver_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_aceptar_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_volver_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_volver_usuariosActionPerformed
        dispose();  //Para volver al menú anterior.
    }//GEN-LAST:event_jButton_volver_usuariosActionPerformed

    private void jButton_aceptar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptar_usuariosActionPerformed
        try {
            //Se crea el objeto la de la clase ListaAlumnos para poder llamar al método modificarAlumnos.
            ListaUsuarios lu = new ListaUsuarios();
            lu.modificarUsuarios();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error, no se ha podido modificar el campo seleccionado de los usuarios", "ERROR", 0);
        }
    }//GEN-LAST:event_jButton_aceptar_usuariosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton_aceptar_usuarios;
    public static javax.swing.JButton jButton_volver_usuarios;
    public static javax.swing.JComboBox<String> jComboBox_menu_modificar_usuarios;
    private javax.swing.JLabel jLabel_titulo_modificar_usuario;
    // End of variables declaration//GEN-END:variables
}
